spring:
  liquibase:
    contexts: prod
  datasource:
    url: jdbc:mysql://localhost:3306/kochbuch?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate

